apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: uppay
  labels:
    app: customer-service
data:
  application.yaml: |
    server:
      port: 8083
    spring:
      application:
        name: customer-service
      datasource:
        url: jdbc:mysql://database-uppay.cn8agw0os9qp.sa-east-1.rds.amazonaws.com:3306/uppay?useSSL=false&serverTimezone=UTC
        username: uppay
        password: uppay0132
      logging:
        level:
          org.springframework.core.env: TRACE
          org.springframework.security: TRACE
      jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    eureka:
      client:
        service-url:
          defaultZone: http://a8e4df1e368a946109b83d1cbb68198c-856949092.sa-east-1.elb.amazonaws.com/eureka/
      instance:
        prefer-ip-address: true
    feign:
      client:
        config:
          default:
            loggerLevel: full
      circuitbreaker:
        enabled: true