apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: uppay
  labels:
    app: customer-service
data:
  application.yaml: |
    server:
      port: 8083
    spring:
      application:
        name: customer-service
      datasource:
        url: jdbc:mysql://mysql-service:3306/uppay
        username: uppay
        password: uppay@0132
      logging:
        level:
          org.springframework.core.env: TRACE
          org.springframework.security: TRACE
      jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-service:8761/eureka/
      instance:
        prefer-ip-address: true
    feign:
      client:
        config:
          default:
            loggerLevel: full
      circuitbreaker:
        enabled: true