server:
  port: 8085
spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://db-uppay.cn8agw0os9qp.sa-east-1.rds.amazonaws.com:3306/uppay?useSSL=false&serverTimezone=UTC
    username: uppay
    password: uppay0132
  logging:
    level:
      org.springframework.core.env: TRACE
      org.springframework.security: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        loggerLevel: full
  circuitbreaker:
    enabled: true