apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: uppay
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-app
          image: ivanazare/user:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
      volumes:
        - name: config-volume
          configMap:
            name: user-config
      restartPolicy: Always