apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: uppay
  labels:
    app: customer-service
spec:
  type: LoadBalancer  # This will create an AWS ELB
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: customer-service