apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: uppay
  labels:
    app: eureka-server
spec:
  type: LoadBalancer  # AWS will create an ELB for this service
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-server