apiVersion: v1
kind: Service
metadata:
  name: fee-service
  namespace: uppay
  labels:
    app: fee-service
spec:
  type: LoadBalancer  # This will create an AWS ELB
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: fee-service