apiVersion: v1
kind: Service
metadata:
  name: loan-service
  namespace: uppay
  labels:
    app: loan-service
spec:
  type: LoadBalancer  # This will create an AWS ELB
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: loan-service