server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uppay
    username: uppay
    password: uppay
  logging:
    level:
      org.springframework.core.env: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect