server:
  port: 5000
spring:
  application:
    name: migration-server
  datasource:
    url: jdbc:mysql://db-uppay.cn8agw0os9qp.sa-east-1.rds.amazonaws.com:3306/uppay?useSSL=false&serverTimezone=UTC
    username: uppay
    password: uppay0132
  logging:
    level:
      org.springframework.core.env: TRACE
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect