apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: uppay
data:
  application.yaml: |
    server:
      port: 8080
    spring:
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: uppay
        password: uppay@0132
      datasource:
        url: jdbc:mysql://mysql-service:3306/uppay
        username: uppay
        password: uppay@0132
      logging:
        level:
          org.springframework.core.env: TRACE
      jpa:
        hibernate:
          ddl-auto: update
        open-in-view: false
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect