apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: uppay
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: <your-eureka-docker-image>  # Replace with your Eureka server image
          ports:
            - containerPort: 8761
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: eureka-server-config