apiVersion: apps/v1
kind: Deployment
metadata:
  name: fee-service
  namespace: uppay
  labels:
    app: fee-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fee-service
  template:
    metadata:
      labels:
        app: fee-service
    spec:
      containers:
        - name: fee-service
          image: 039074742130.dkr.ecr.sa-east-1.amazonaws.com/fee:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: fee-service-config
      restartPolicy: Always