apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-service
  namespace: uppay
  labels:
    app: loan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-service
  template:
    metadata:
      labels:
        app: loan-service
    spec:
      containers:
        - name: loan-service
          image: your-ecr-repo/loan-service:latest  # Replace with your actual ECR image
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: loan-app-config
      restartPolicy: Always