apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-server
  namespace: uppay
  labels:
    app: migration-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-server
  template:
    metadata:
      labels:
        app: migration-server
    spec:
      containers:
        - name: migration-server
          image: 039074742130.dkr.ecr.sa-east-1.amazonaws.com/migration:latest  # Replace with your actual image
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/
      volumes:
        - name: config-volume
          configMap:
            name: migration-server-config