apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: uppay
data:
  my.cnf: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp=1
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci