apiVersion: v1
kind: Service
metadata:
  name: migration-service
  namespace: uppay
spec:
  selector:
    app: migration
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Use LoadBalancer or NodePort if external access is needed